name: CI - Build & Push Docker Image to ACR

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore app/ReferenceApi/ReferenceApi.csproj

      - name: Build application
        run: dotnet build app/ReferenceApi/ReferenceApi.csproj --configuration Release --no-restore

      - name: Run tests
        run: dotnet test app/ReferenceApi/ReferenceApi.csproj --no-build --verbosity normal

      - name: Build Docker image
        run: |
          cd app/ReferenceApi
          docker build -t reference-api:${{ github.sha }} .

      #Login to ACR (ADMIN USER METHOD)
      - name: Docker login to ACR
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login \
            ${{ secrets.ACR_LOGIN_SERVER }} \
            -u ${{ secrets.ACR_USERNAME }} \
            --password-stdin

      #Tag & push image
      - name: Push Docker image to ACR
        run: |
          docker tag reference-api:${{ github.sha }} \
            ${{ secrets.ACR_LOGIN_SERVER }}/reference-api:${{ github.sha }}

          docker push \
            ${{ secrets.ACR_LOGIN_SERVER }}/reference-api:${{ github.sha }}
